// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMp5BynbwH7suA_S123vkUC9RrYf7L5n0',
    appId: '1:741366957632:web:64518bd8b313123ce5c1a5',
    messagingSenderId: '741366957632',
    projectId: 'currensee-951ce',
    authDomain: 'currensee-951ce.firebaseapp.com',
    storageBucket: 'currensee-951ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQiVJ3VOZtbQCyHQIjCvzk6-LsMA7B_TU',
    appId: '1:741366957632:android:c3b918dfa6fdbb8be5c1a5',
    messagingSenderId: '741366957632',
    projectId: 'currensee-951ce',
    storageBucket: 'currensee-951ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv1Ge5BALixE3jv6NumJmdvj8qcmMtY40',
    appId: '1:741366957632:ios:df0e9a53b7dab2fbe5c1a5',
    messagingSenderId: '741366957632',
    projectId: 'currensee-951ce',
    storageBucket: 'currensee-951ce.firebasestorage.app',
    iosBundleId: 'com.example.currensee',
  );
}
